name: CI and Release

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
    branches: [master]

env:
  VERSION_OVERRIDE: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential
        elif [ "${{ runner.os }}" = "Windows" ]; then
          choco install wixtoolset -y
        fi

    - name: Configure project
      run: cmake -B build
      
    - name: Build project
      run: cmake --build build --config Release

  package:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            generator: "DEB;RPM"
          - os: windows-latest
            generator: "WIX"
          - os: macos-latest
            generator: "DragNDrop"
    steps:
    - uses: actions/checkout@v4
    
    - name: Clean build directory
      run: |
        rm -rf build/*
        mkdir -p build

    - name: Install packaging tools
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y rpm
        elif [ "${{ runner.os }}" = "Windows" ]; then
          choco install wixtoolset -y
        fi

    - name: Configure CPack
      run: cmake -B build -DCPACK_GENERATOR="${{ matrix.generator }}"
      
    - name: Build packages
      run: cmake --build build --target package
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-packages
        path: |
          build/*.deb
          build/*.rpm
          build/*.msi
          build/*.dmg
          build/*.tar.gz
          build/*.zip
        if-no-files-found: error
        retention-days: 1
        compression-level: 1

  release:
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: '*-packages/*'
        merge-multiple: true
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/*.deb
          artifacts/*.rpm
          artifacts/*.msi
          artifacts/*.dmg
          artifacts/*.tar.gz
          artifacts/*.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
