name: CI and Release

on:
  push:
    branches: [master]
    tags: ['v*.*.*']  # Более строгий формат тегов
  pull_request:
    branches: [master]

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    - name: Install dependencies
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential
        elif [ "${{ runner.os }}" = "Windows" ]; then
          choco install nsis -y
        fi

    - name: Configure project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DVERSION_OVERRIDE=${{ env.VERSION }}
      
    - name: Build project
      run: cmake --build build --config Release

  package:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            generator: "DEB"
          - os: windows-latest
            generator: "NSIS"
          - os: macos-latest
            generator: "DragNDrop"
    steps:
    - uses: actions/checkout@v4
    
    - name: Clean build (Linux/macOS)
      if: runner.os != 'Windows'
      run: rm -rf build/* && mkdir -p build
      shell: bash

    - name: Clean build (Windows)
      if: runner.os == 'Windows'
      run: Remove-Item -Path "build\*" -Recurse -Force -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Path "build" -Force | Out-Null
      shell: pwsh

    - name: Configure CPack
      run: cmake -B build -DCPACK_GENERATOR="${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=Release -DVERSION_OVERRIDE=${{ env.VERSION }}
      
    - name: Build package
      run: cmake --build build --target package
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-package
        path: |
          build/*.deb
          build/*.exe
          build/*.dmg
          build/*.tar.gz
        if-no-files-found: warn
        retention-days: 1

  release:
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: '*-package/*'
        merge-multiple: true
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        files: |
          artifacts/*.deb
          artifacts/*.exe
          artifacts/*.dmg
          artifacts/*.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
